# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37fd24960f22164bf4cf8c648b721efb"
name = "focused-strategy-app"
handle = "focused-strategy-app-8"
application_url = "https://focused-strategy-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ptinilesh.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tried-kathy-funeral-interventions.trycloudflare.com/auth/callback",
  "https://tried-kathy-funeral-interventions.trycloudflare.com/auth/shopify/callback",
  "https://tried-kathy-funeral-interventions.trycloudflare.com/api/auth/callback",
  "https://focused-strategy-app.fly.dev/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = true
